In [1]:
import pandas as pd

In [2]:
drugbank_path = '/DATA/DATANAS2/rhh25/dti_dataset/drugbank/'

drugbank_df = pd.read_csv(drugbank_path + 'database.csv')

In [23]:
drugcomb_df = pd.read_csv('/DATA/DATANAS2/rhh25/Cellhit/data/metadata/drugcombs_scored.csv')
drugcomb_df.drop_duplicates(subset=['Drug1', 'Drug2', 'Cell line'], inplace=True)
drugcomb_df

,ID,Drug1,Drug2,Cell line,ZIP,Bliss,Loewe,HSA
0,1,5-FU,ABT-888,A2058,1.720,6.260,-2.750,5.540
4,5,5-FU,AZD1775,A2058,12.290,15.770,10.400,18.660
8,9,5-FU,BEZ-235,A2058,4.010,3.380,3.210,7.140
12,13,5-FU,BORTEZOMIB,A2058,-3.990,-0.430,-6.580,-2.890
16,17,5-FU,DASATINIB,A2058,-5.790,4.500,8.560,9.600
...,...,...,...,...,...,...,...,...
498859,498860,Rotenone,Valproic acid sodium salt,DIPG25,-6.545,-5.280,-6.811,2.909
498861,498862,Cyanein,Valproic acid sodium salt,DIPG25,1.320,-1.091,-16.157,1.139
498862,498863,Erlotinib,Valproic acid sodium salt,DIPG25,-15.768,-15.776,-25.465,-6.212
498863,498864,Bafilomycin A1,Valproic acid sodium salt,DIPG25,2.208,10.567,-9.455,1.525
498864,498865,Mebendazole,Valproic acid sodium salt,DIPG25,6.807,11.948,-18.311,1.149

In [26]:
cell_expression = pd.read_csv('/DATA/DATANAS2/rhh25/Cellhit/data/ccle/OmicsExpressionExpectedCountHumanAllGenesStranded.csv')

In [27]:
cell_expression

,Unnamed: 0,SequencingID,ModelID,IsDefaultEntryForModel,ModelConditionID,IsDefaultEntryForMC,TSPAN6 (7105),TNMD (64102),DPM1 (8813),SCYL3 (57147),...,ENSG00000288716.1,ENSG00000288717.1,ENSG00000288718.1,ENSG00000288719.1,ENSG00000288720.1,ENSG00000288721.1,F8A1 (8263),ENSG00000288723.1,ENSG00000288724.1,ENSG00000288725.1
0,0,CDS-010xbm,ACH-001113,Yes,MC-001113-k2lR,Yes,2099,0,4455,815,...,0,1,0,3,0,57,353,3,0,0
1,1,CDS-02TzJp,ACH-001289,Yes,MC-001289-BpdI,Yes,2226,12,3235,511,...,0,2,0,1,0,17,375,0,0,5
2,2,CDS-0693hw,ACH-001339,Yes,MC-001339-5nRN,Yes,1355,0,6885,806,...,0,0,3,0,0,16,207,1,0,0
3,3,CDS-07Plat,ACH-001619,No,MC-001619-IR6I,No,3410,0,2099,385,...,0,0,0,0,0,13,991,0,0,0
4,4,CDS-08FOcu,ACH-001979,Yes,MC-001979-E3qW,Yes,2578,0,1705,682,...,0,1,0,0,0,13,639,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1749,1749,CDS-zsS3zE,ACH-002669,Yes,MC-002669-Ivra,Yes,1329,0,5291,377,...,0,2,37,0,11,24,3670,10,0,0
1750,1750,CDS-zsp0NA,ACH-001858,Yes,MC-001858-c43i,Yes,4192,0,6621,793,...,0,0,11,2,1,75,2406,14,0,0
1751,1751,CDS-zvrgDc,ACH-001997,Yes,MC-001997-n8wz,Yes,36453,0,57249,6840,...,0,0,18,6,72,280,9957,11,0,9
1752,1752,CDS-zvw4zv,ACH-003297,Yes,MC-003297-yuio,Yes,3358,0,12586,380,...,0,0,0,0,0,29,228,0,0,0
1753,1753,CDS-zx92JS,ACH-000052,Yes,MC-000052-uUW6,Yes,2883,0,3210,898,...,0,0,2,7,25,122,1387,0,0,0